### ISSUE TITLE
你好，我是做iOS的，拉入你的3个文件和图片到xcode工程，允许崩溃啊

### ISSUE THREAD

**Issue by mrzhao12** [023proz/tilted-image-correction#1]
你好，我是做iOS的，拉入你的3个文件和图片到xcode工程，允许崩溃啊，求解

**Comment by WOWSCpp** [comment]
我没有在ios环境下搞过。。
崩溃原因找到了吗？

**Comment by LaughingVzr** [comment]
> 你好，我是做iOS的，拉入你的3个文件和图片到xcode工程，允许崩溃啊，求解

可以通过cmake生成一下Xcode项目，然后再按照生成的项目往你的项目中移植。
